In [ ]:
张量运算

1、逐元素运算

In [7]:
import numpy as np
a = np.array([
    [1, 1],
    [1, 1]
])
b = np.array([
    [1, 2],
    [3, 4]
])
# 逐元素相加
a + b

array([[2, 3],
       [4, 5]])

In [10]:
# 逐元素相减
b - a

array([[0, 1],
       [2, 3]])

In [12]:
# 逐元素相乘
a * b

array([[1, 2],
       [3, 4]])

In [14]:
# 逐元素相除
b / a

array([[1., 2.],
       [3., 4.]])

2、张量点积:点前面张量逐行和点后面的逐列对应相加

In [17]:
c = np.array([
    [1, 2],
    [3, 4]
])
d = np.array([
    [1, 2],
    [3, 4]
])
np.dot(c, d)

array([[ 7, 10],
       [15, 22]])

3、张量变形

In [20]:
e = np.array([
    [7, 10],
    [15, 22]
])
e.shape

(2, 2)

In [22]:
e.ndim

2

In [25]:
e.reshape(1, 4)

array([[ 7, 10, 15, 22]])

In [27]:
e.ndim

2

In [29]:
e.reshape(4, 1)

array([[ 7],
       [10],
       [15],
       [22]])

In [30]:
e.ndim

2